// svelte/src/App.svelte
<script lang="ts">
    import { onMount } from "svelte";
    import Functional from "./lib/Functional.svelte";
    import Card from "./lib/Card.svelte";
    import { type APICallResult, letsCallAPI } from "../../intermediate_api";

    let v: undefined | APICallResult; 
    onMount(async () => {
        v = await letsCallAPI();
    });
</script>

<main class="w-screen h-screen flex flex-col gap-y-2">
    <Functional/>
    <div class="w-screen h-screen flex justify-center items-center">
        <Card apiResult={v}/>
    </div>
</main>

// react/src/App.tsx
import { useState, useEffect } from 'react'
import Funcional from "./components/Functional";
import Card from './components/Cards';
import { type APICallResult, letsCallAPI } from "../../intermediate_api";

function App() {
  const [result, setRes] = useState<APICallResult | undefined>();

  useEffect(() => {
    letsCallAPI()
      .then(v  => {
        setRes(j => {
          j = v;
          return j;
        })
      })
  }, []);

  return (
    <>
      <Funcional/>
      <div id="cards-space" className='w-screen h-screen flex justify-center items-center'>
        <Card result={result}/>
      </div>
    </>
  )
}

export default App
